# Simulate performance counter output
Write-Output "\Processor(_Total)\% Processor Time : 123.45"
Write-Output "\System\Processor Queue Length : 123.45"
Write-Output "\Memory\Available Bytes : 123.45"
Write-Output "\Memory\Pages/sec : 123.45"
Write-Output "\PhysicalDisk(_Total)\% Disk Time : 123.45"
Write-Output "\ASP.NET Applications(__Total__)\Requests/Sec : 123.45"
Write-Output "\ASP.NET\Application Restarts : 123.45"
Write-Output "\ASP.NET\Request Wait Time : 123.45"
Write-Output "\ASP.NET\Requests Queued : 123.45"
Write-Output "\.NET CLR Exceptions(_Global_)\# of Exceps Thrown / sec : 123.45"
Write-Output "\.NET CLR Memory(_Global_)\# Total committed Bytes : 123.45"
Write-Output "\Web Service(_Total)\Get Requests/sec : 123.45"
Write-Output "\Web Service(_Total)\Post Requests/sec : 123.45"
Write-Output "\Web Service(_Total)\Current Connections : 123.45"